spring:
  datasource:
    url: jdbc:postgresql://192.168.31.107:5432/postgres
    username: postgres
    password: sqlsql111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    com.xiao.cs209a_project: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG